// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {service} from '../models';
import {vault} from '../models';

export function AddVaultEntry(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<void>;

export function BindRepo(arg1:string):Promise<void>;

export function DeleteVaultEntry(arg1:string,arg2:string):Promise<void>;

export function GetAppConfig():Promise<config.Snapshot>;

export function GetRepoStatus():Promise<service.RepoStatus>;

export function InitLocalVault(arg1:string):Promise<void>;

export function ListVaultEntries(arg1:string):Promise<Array<vault.Entry>>;

export function Pull():Promise<void>;

export function Push():Promise<void>;

export function ReloadConfig():Promise<void>;

export function Sync(arg1:string):Promise<void>;

export function UpdateVaultEntry(arg1:string,arg2:vault.Entry):Promise<void>;
