// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddVaultEntry(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['AddVaultEntry'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function BindRepo(arg1) {
  return window['go']['app']['App']['BindRepo'](arg1);
}

export function CreateVaultSpace(arg1, arg2) {
  return window['go']['app']['App']['CreateVaultSpace'](arg1, arg2);
}

export function DeleteVaultEntry(arg1, arg2) {
  return window['go']['app']['App']['DeleteVaultEntry'](arg1, arg2);
}

export function DeleteVaultSpace(arg1, arg2) {
  return window['go']['app']['App']['DeleteVaultSpace'](arg1, arg2);
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetRepoStatus() {
  return window['go']['app']['App']['GetRepoStatus']();
}

export function InitLocalVault(arg1) {
  return window['go']['app']['App']['InitLocalVault'](arg1);
}

export function ListVaultEntries(arg1, arg2) {
  return window['go']['app']['App']['ListVaultEntries'](arg1, arg2);
}

export function ListVaultSpaces(arg1) {
  return window['go']['app']['App']['ListVaultSpaces'](arg1);
}

export function MoveVaultEntries(arg1, arg2, arg3) {
  return window['go']['app']['App']['MoveVaultEntries'](arg1, arg2, arg3);
}

export function Pull() {
  return window['go']['app']['App']['Pull']();
}

export function Push() {
  return window['go']['app']['App']['Push']();
}

export function ReloadConfig() {
  return window['go']['app']['App']['ReloadConfig']();
}

export function RenameVaultSpace(arg1, arg2, arg3) {
  return window['go']['app']['App']['RenameVaultSpace'](arg1, arg2, arg3);
}

export function Sync(arg1) {
  return window['go']['app']['App']['Sync'](arg1);
}

export function UpdateAppConfig(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateAppConfig'](arg1, arg2, arg3);
}

export function UpdateSSHCredentials(arg1, arg2) {
  return window['go']['app']['App']['UpdateSSHCredentials'](arg1, arg2);
}

export function UpdateVaultEntry(arg1, arg2) {
  return window['go']['app']['App']['UpdateVaultEntry'](arg1, arg2);
}
